name: Prettier Auto-Format

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  prettier-frontend:
    name: Prettier Frontend
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install dependencies
        working-directory: ./frontend
        run: npm install

      - name: Run Prettier and Format Code
        working-directory: ./frontend
        run: npm run format

  prettier-backend:
    name: Prettier Backend
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install dependencies
        working-directory: ./backend
        run: npm install

      - name: Run Prettier and Format Code
        working-directory: ./backend
        run: npm run format